version: '2.2'

services:
  ns:
    build: ns
    image: ${DOCKER_REGISTRY}desec/slave-ns:latest
    init: true
    cap_add:
    - NET_ADMIN
    environment:
    - DESECSLAVE_CARBONSERVER
    - DESECSLAVE_CARBONOURNAME
    - DESECSLAVE_NS_APIKEY
    networks:
      middle:
        ipv4_address: 10.16.2.2
      rear:
      rearreplication:
        ipv4_address: 10.16.3.3
    sysctls:
      net.ipv4.icmp_echo_ignore_broadcasts: 0
    volumes:
    - ns:/var/lib/powerdns
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/ns"
    restart: unless-stopped

  dnsdist:
    build: dnsdist
    image: ${DOCKER_REGISTRY}desec/slave-dnsdist:latest
    init: true
    depends_on:
    - ns
    ports:
    - "53:53"
    - "53:53/udp"
    environment:
    - DESECSLAVE_CARBONSERVER
    - DESECSLAVE_CARBONOURNAME
    networks:
      front:
        ipv4_address: 10.16.0.2
        ipv6_address: ${DESECSLAVE_IPV6_ADDRESS}
      middle:
        ipv4_address: 10.16.2.3
      rearmonitoring_dnsdist:
        ipv4_address: 10.16.4.10
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/dnsdist"
    restart: unless-stopped

  openvpn-client:
    build: openvpn-client
    image: desec/openvpn-client:latest
    init: true
    cap_add:
    - NET_ADMIN
    environment:
    - DESECSTACK_VPN_SERVER
    volumes:
    - ./openvpn-client/secrets:/etc/openvpn/secrets:ro
    - openvpn-client_logs:/var/log/openvpn
    networks:
      rearreplication:
        ipv4_address: 10.16.3.2
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/openvpn-client"
    restart: unless-stopped

  openvpn-client_monitor:
    image: kumina/openvpn-exporter:v0.2.2
    init: true
    depends_on:
    - openvpn-client
    volumes:
    - openvpn-client_logs:/var/log/openvpn:ro
    networks:
    - rearmonitoring_openvpn-client
    command: -openvpn.status_paths /var/log/openvpn/openvpn-status.log
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/openvpn-client_monitor"
    restart: unless-stopped

  replicator:
    build: replicator
    image: desec/replicator:latest
    init: true
    cap_add:
    - NET_ADMIN
    depends_on:
    - openvpn-client
    - ns
    environment:
    - DESECSLAVE_NS_APIKEY
    - DESECSTACK_VPN_SERVER
    networks:
      rearreplication:
        ipv4_address: 10.16.3.4
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/replicator"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    init: true
    ports:
    - "127.0.0.1:9090:9090"
    volumes:
    - ./prometheus/conf:/etc/prometheus:ro
    - prometheus:/prometheus
    networks:
      rearmonitoring_openvpn-client:
      rearmonitoring_dnsdist:
        ipv4_address: 10.16.4.11
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/prometheus"
    restart: unless-stopped

volumes:
  ns:
  prometheus:
  openvpn-client_logs:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  front:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.0.0/24
        gateway: 10.16.0.1
      - subnet: ${DESECSLAVE_IPV6_SUBNET}
  middle:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.2.0/24
        gateway: 10.16.2.1
  rear:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.1.0/24
        gateway: 10.16.1.1
  rearreplication:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.3.0/24
        gateway: 10.16.3.1
  rearmonitoring_openvpn-client:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.16.4.0/29
          gateway: 10.16.4.1
  rearmonitoring_dnsdist:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.16.4.8/29
          gateway: 10.16.4.9
