version: '2'

services:
  db:
    build: db
    image: desec/dedyn-dbslave:latest
    volumes:
    - db_mysql:/var/lib/mysql
    environment:
    - DESECSLAVE_DB_PASSWORD_pdns
    - DESECSLAVE_ID
    - DESECSTACK_DBMASTER
    - DESECSTACK_DBMASTER_USERNAME_replication
    - DESECSTACK_DBMASTER_PASSWORD_replication
    - DESECSTACK_DBMASTER_SUBJECT_replication
    volumes:
    - ${DESECSLAVE_CERT_FOLDER}:/etc/ssl/private
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/db"
    restart: unless-stopped

  ns:
    build: ns
    image: desec/dedyn-nsslave:latest
    environment:
    - DESECSLAVE_DB_PASSWORD_pdns
    depends_on:
    - db
    ports:
    - "53:53"
    - "53:53/udp"
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/ns"
    restart: unless-stopped

volumes:
  db_mysql:
