version: '2.2'

services:
  ns:
    build: ns
    image: ${DOCKER_REGISTRY}desec/slave-ns:latest
    init: true
    environment:
    - DESECSLAVE_CARBONSERVER
    - DESECSLAVE_CARBONOURNAME
    networks:
      middle:
        ipv4_address: 10.16.2.2
      rear:
    volumes:
    - ns:/var/lib/powerdns
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/ns"
    restart: unless-stopped

  dnsdist:
    build: dnsdist
    image: ${DOCKER_REGISTRY}desec/slave-dnsdist:latest
    init: true
    depends_on:
    - ns
    ports:
    - "53:53"
    - "53:53/udp"
    networks:
      front:
        ipv4_address: 10.16.0.2
        ipv6_address: ${DESECSLAVE_IPV6_ADDRESS}
      middle:
        ipv4_address: 10.16.2.3
    logging:
      driver: "syslog"
      options:
        tag: "desec-slave/dnsdist"
    restart: unless-stopped

volumes:
  ns:

networks:
  # Note that it is required that the front network ranks lower (in lexical order by
  # name) than the other networks. See https://github.com/docker/docker/issues/27101
  front:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.0.0/24
        gateway: 10.16.0.1
      - subnet: ${DESECSLAVE_IPV6_SUBNET}
  middle:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.2.0/24
        gateway: 10.16.2.1
  rear:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.16.1.0/24
        gateway: 10.16.1.1
